const data = {
  code: 0,
  res: {
    nodes: [
      {
        id: '3105636077',
        size: null,
        color: null,
        x: 160,
        y: 140,
        icon: 'RadarChartOutlined',
        name: '节点1',
        alias: null,
        description: null,
        type: 'RESOURCE_CATEGORY_APPLICATION',
        category: null,
        ip: null,
        mac: null,
        belongToBizId: null,
        nodePoints: [
          {
            id: 'd09eb112-7f88-438d-8d9c-7e1f82703995',
            group: 'top',
          },
          {
            id: 'ea604720-89b3-40ce-9b8b-7d1184c3c908',
            group: 'right',
          },
          {
            id: 'c3ff4d01-a577-4fc8-9c71-37199332a78e',
            group: 'bottom',
          },
          {
            id: '7522ab03-857a-475e-956f-0b46d761380a',
            group: 'left',
          },
        ],
        ipv6: null,
        typeStr: null,
        monitorCpu: null,
        monitorMem: null,
        healthDegree: null,
        administrator: null,
        phone: null,
        brand: null,
        manufacturer: null,
        manufacturerResponsiblePerson: null,
        manufacturerPhone: null,
        status: null,
        eventId: null,
        eventSeverity: null,
        eventInfo: null,
      },
      {
        id: '3105636079',
        size: null,
        color: null,
        x: 426,
        y: 140,
        icon: null,
        name: '节点2',
        alias: null,
        description: null,
        type: 'RESOURCE_CATEGORY_APPLICATION',
        category: null,
        ip: null,
        mac: null,
        belongToBizId: null,
        nodePoints: [
          {
            id: 'd09eb112-7f88-438d-8d9c-7e1f82703995',
            group: 'top',
          },
          {
            id: 'ea604720-89b3-40ce-9b8b-7d1184c3c908',
            group: 'right',
          },
          {
            id: 'c3ff4d01-a577-4fc8-9c71-37199332a78e',
            group: 'bottom',
          },
          {
            id: '7522ab03-857a-475e-956f-0b46d761380a',
            group: 'left',
          },
        ],
        ipv6: null,
        typeStr: null,
        monitorCpu: null,
        monitorMem: null,
        healthDegree: null,
        administrator: null,
        phone: null,
        brand: null,
        manufacturer: null,
        manufacturerResponsiblePerson: null,
        manufacturerPhone: null,
        status: null,
        eventId: null,
        eventSeverity: null,
        eventInfo: null,
      },
    ],
    edges: [
      {
        id: '3105636243',
        name: null,
        source: '3105636077',
        sourcePoint: 'ea604720-89b3-40ce-9b8b-7d1184c3c908',
        sourcePort: null,
        sourcePortIndex: null,
        sourcePortStatus: '不可用',
        sourcePortStatusColor: 'gray',
        target: '3105636079',
        targetPoint: '7522ab03-857a-475e-956f-0b46d761380a',
        targetPort: null,
        targetPortIndex: null,
        targetPortStatus: '不可用',
        targetPortStatusColor: 'gray',
        linkStatus: '不可用',
        linkStatusColor: 'gray',
        type: null,
        shape: null,
        curveOffset: null,
        controlPoints: null,
      },
    ],
  },
  error: null,
  trace: null,
};

// 获取拓扑图节点和连线
export function getTopologyDetail() {
  return new Promise((resolve) => {
    resolve(data);
  });
}
